- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Make sure docker is running
      service:
        name: docker
        state: started

